 <section id="fourth">
        <div class="container">

            <h1>About</h1>

            <div class="content">

            	<div class = "libs">
                
                <h2>Libraries Used - Professor Kostin's "Long-Scrolly" Template</h2>
                <p>I kept most of it the same, however I added the title to the center of the nav bar, and put the Home button on the right.</p>
                <h2>Web Fonts Used - Quicksand & Nunito</h2>
                <p>Both these fonts are google fonts and can be found below.</p>
                <p><a href="https://fonts.google.com/specimen/Quicksand">Quicksand</a> </p>
                <p> <a href="https://fonts.google.com/specimen/Nunito">Nunito</a></p>
                <p>The look of the web fonts fit the feel of a soft informational webpage. I didn't want a font that looked too official and stale, nor a font that didn't look serious.</p>
                <p> The two fonts are similar, but different enough that there is some contrast between the headers and paragraphs.</p>
                <h2>Inspiration</h2>
                <p>The inspiration for my website came from <a href="https://grovemade.com/">Grovemade</a>. It looks very simple, but everything just pops. </p>
                <p> Additionally I really like the title page, and I tried to replicate that in my website. It's half a Z-pattern, with the footer only completing the pattern at the bottom of the last page.</p>

                
            </div>
                <div class = "links">

                	<h2>Links</h2>
                	<h3>Web Page Content</h3>
                	<ul>
                		<li><a href = "http://urcsc174.org/bangkok/jerrydai.php"> Jerry Dai </a></li>
                		<li><a href = "http://urcsc174.org/milan/assignment5/alihashim.php"> Ali Hashim </a></li>
                	</ul>

                	<h3>Photo Credit</h3>
                	<ul>
                		<li><a href="https://www.maxrivephotography.com/p/greenland-2017">Max Rive Photography</a></li>
                	</ul>

                </div>




            </div><!-- .content -->

       </div><!-- .container -->

    </section>