 <section id="fourth">
        <div class="container">

            <h1>About</h1>

            <div class="content">

                
                <h3>Libraries Used - Professor Kostin's "Long-Scrolly" Template</h3>
                <p>I kept most of it the same, however I added the title to the center of the nav bar, and put the Home button on the right.</p>
                <h3>Web Fonts Used - Quicksand & Nunito</h3>
                <p>Both these fonts are google fonts and can be found here.</p>
                <p><a href="https://fonts.google.com/specimen/Quicksand">Quicksand</a> </p>
                <p> <a href="https://fonts.google.com/specimen/Nunito">Nunito</a></p>
                <p>The look of the web fonts fit the feel of a soft informational webpage. I didn't want a font that looked too official and stale, nor a font that didn't look serious. The two fonts are similar, but different enough that there is some contrast between the different text.</p>
                <h3>Inspiration</h3>
                <p>The inspiration for my website came from <a href="https://grovemade.com/">Grovemade</a>. It looks very simply, but everything just pops. It makes good use of the "Z-Pattern" at the end. Overall it does a good job not overwhelming the user with content. </p>
                
            </div><!-- .content -->

       </div><!-- .container -->

    </section>