<section id="third">
        <div class="container">

            <h1>Ali Hashim</h1>

            
            <div class="content">

            	<div class = "right">
                <img src="img/ali.jpg" alt="Ali" width="350" height="450">
                <h2 >Skills</h2>
					
				
					<h3 >Computer Skills</h3>
					<ul>
						<li>Adobe Experience Design</li>
						<li>Adobe Illustrator</li>
						<li>Adobe Photoshop</li>
						<li>HTML & CSS</li>
						<li>Java</li>
						<li>JavaScript</li>
						<li>Matlab</li>
						<li>Microsoft Office</li>
						<li>Python</li>
						<li>Swift</li>
					</ul>
				
				
            	</div>
                
                <h2>About Me</h2>
					<div class="tagline"><p>
						I’m a twenty-one year old optical engineer studying at the University of Rochester.</p></div> <p> I am passionate about manipulating light to create great products! I am also a self-taught mobile application developer and graphic designer and am looking to apply my skills to serve a design, testing, and manufacturing role.
					</p>
				
			
				<h2 >Experience</h2>


					<h3 >Cymer, An ASML Company Optical Engineering Intern</h3>
					<p>
						Developed and conducted experiments in a cleanroom environment to characterize and determine if polarization components are capable of scaling into production for EUV lithography systems.
					</p>
				
					<h3>University of Rochester Optics Lab Teaching Assistant</h3>
					<p>Helped teach, grade, and direct students how to learn the basic laboratory techniques of geometrical optics, physical optics, and how to write lab reports.
					</p>
				
					<h3 >Laboratory for Laser Energetics Research Intern</h3>
					<p>Designed and developed an image analysis program in MATLAB with openCV for an x-ray spectrometer implemented in LLE lasers to characterize the high-energy-density plasmas created in fusion experiments.
					</p>
				
					<h3 >University of Rochester Medical Center Research Assistant</h3>
					<p>Conducted biological lab techniques to determine the environmental stressors for age-related macular disorders. </p>
			
			<!-- four -->

			
				
		
            </div><!-- .content -->

       </div><!-- .container -->

    </section>