
    <section id="second">
        <div class="container">

            <h1>Jerry Dai</h1>

            <div class="content">

                

                <h2>About Me</h2>
                <div class="tagline"><p>
                    Hi my name is Jerry and I am a junior at the U of R. I'm from Queens, NY but my parents moved to Brooklyn from China when they were in their early 20s.</p></div><p> My hobbies are music, lifting, and cooking. My favorite foods include halal, vodka slices, and sushi. I am double majoring in Business and Computer Science and I'm interested in working in finance in the future. </p>
                    <p> Next summer, I will be interning at EY LLP as part of the FSO Technology Advisor Program.
                </p>

                <h2>Experience</h2>

                <h3>Associate - Greater Flushing Chamber of Commerce</h3>
                <div class="tagline"><p>
                    I designed and programmed the new web portal for the "Flushing Neighborhood 360" marketing campaign.</p></div> <p> In addition, I worked with local business owners to attract more visitors to the neighborhood, most notably by helping organize a night market featuring the community's small businesses.
                </p>
                
                <h3>Student Success Intern - Aspire</h3>
               <div class="tagline"> <p>
                    At the start-up Aspire, I managed email marketing campaigns and outreach to student groups from various universities.</p></div> <p> I also took part in some product-testing and product-feedback studies.
                </p>
                
                <h3>Business Finance Intern - NYC Seminar and Conference Center</h3>
                <div class="tagline"><p>
                    I performed spreadsheet analysis as part of the firm's application for a NY Business Development grant.</p></div> <p> I helped estimate break-even costs for products with variable pricing and also worked with the senior technical director to help set up server room software/hardware.
                </p>
            </div><!-- .content -->

       </div><!-- .container -->

    </section>
