
    <nav class="main-menu">
        <ul>
            
            <li><a href="#second">Jerry</a></li>
            <li><a href="#third">Ali</a></li>
            <li><a href="#fourth">About</a></li>
            <div class="home">
            <li><a href="#first">Home</a></li>    
            </div>
            
        <div class = "CSC">
        	<li><a href="#first"> CSC 174</a></li>
    		</div>
    	</ul>

    </nav>