<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name ="viewport" content ="width=device-width">
    <title>Cj Van Huben's Assignment06</title>
   <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="css/long-scrolly.css">
    <link rel="stylesheet" href="css/styles.css">
</head>